SocialMedia/Models/User.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Web.Security;

namespace SocialMedia.Models
{
    [Table("Users")]
    public class User
    {
        public User()
        {
            Roles = new List<Role>();
        }

        public string emailHash()
        {
            return FormsAuthentication.HashPasswordForStoringInConfigFile(Email.Trim().ToLower(), "MD5").ToLower();
        }

        [Key]
        [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }

        [Required]
        public string Username { get; set; }

        [Required]
        public string Email { get; set; }

        [Required]
        public string Password { get; set; }

        public virtual ICollection<Role> Roles { get; set; }
    }
}

SocialMedia/Controllers/FollowController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SocialMedia.Repositories;
using SocialMedia.Models;

namespace SocialMedia.Controllers
{
    public class FollowController : Controller
    {
        //
        // GET: /Follow/
        public ActionResult Index()
        {
            return View();
        }

        //
        // POST: /Follow/Add
        [HttpPost]
        public ActionResult Add(int FollowedUser, int FollowsUser, string ReturnUrl)
        {
            try
            {
                FollowRepository followRepository = RepositoryFactory.GetFollowRepository();
                UserRepository userRepository = RepositoryFactory.GetUserRepository();

                User userFollows = userRepository.GetUserById(FollowsUser);
                User userFollowed = userRepository.GetUserById(FollowedUser);

                Follow newFollow = new Follow()
                {
                    UserFollowed = userFollowed,
                    UserFollows = userFollows
                };

                followRepository.Add(newFollow);

                return Redirect(ReturnUrl);
            }
            catch
            {
                return Redirect(ReturnUrl);
            }
        }

        //
        // POST: /Follow/Remove
        [HttpPost]
        public ActionResult Remove(int FollowedUser, int FollowsUser, string ReturnUrl)
        {
            try
            {
                FollowRepository followRepository = RepositoryFactory.GetFollowRepository();
                UserRepository userRepository = RepositoryFactory.GetUserRepository();

                User userFollows = userRepository.GetUserById(FollowsUser);
                User userFollowed = userRepository.GetUserById(FollowedUser);

                followRepository.Remove(userFollows.Id, userFollowed.Id);

                return Redirect(ReturnUrl);
            }
            catch
            {
                return Redirect(ReturnUrl);
            }
        }

    }
}

SocialMedia/Controllers/LikeController.cs
using SocialMedia.Repositories;
using SocialMedia.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SocialMedia.Controllers
{
    public class LikeController : Controller
    {
        //
        // GET: /Like/
        public ActionResult Index()
        {
            return View();
        }

        //
        // POST: /Like/Add/Id
        [Authorize]
        [HttpPost]
        public ActionResult Add(int UserId, int PostId, string ReturnUrl)
        {
            try
            {
                UserRepository userRepository = RepositoryFactory.GetUserRepository();
                PostRepository postRepository = RepositoryFactory.GetPostRepository();
                LikeRepository likeRepository = RepositoryFactory.GetLikeRepository();

                User currentUser = userRepository.GetUserById(UserId);
                Post currentPost = postRepository.GetPostById(PostId);

                Like newLike = new Like()
                {
                    User = currentUser,
                    Post = currentPost
                };

                likeRepository.Add(newLike);

                return Redirect(ReturnUrl);
            }
            catch
            {
                return Redirect(ReturnUrl);
            }
        }

        //
        // POST: /Like/Remove/Id
        [Authorize]
        [HttpPost]
        public ActionResult Remove(int UserId, int PostId, string ReturnUrl)
        {
            try
            {
                LikeRepository likeRepository = RepositoryFactory.GetLikeRepository();

                likeRepository.Remove(UserId, PostId);

                return Redirect(ReturnUrl);
            }
            catch
            {
                return Redirect(ReturnUrl);
            }
        }

    }
}

SocialMedia/Controllers/ReplyController.cs
using SocialMedia.Repositories;
using SocialMedia.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SocialMedia.Models;

namespace SocialMedia.Controllers
{
    public class ReplyController : Controller
    {

        //
        // POST: /Post/Add
        [HttpPost]
        public ActionResult Add(string ReplyContent, int UserId, int PostId, string returnUrl)
        {
            try
            {
                UserRepository userRepository = RepositoryFactory.GetUserRepository();
                PostRepository postRepository = RepositoryFactory.GetPostRepository();
                ReplyRepository replyRepository = RepositoryFactory.GetReplyRepository();

                User currentUser = userRepository.GetUserById(UserId);
                Post currentPost = postRepository.GetPostById(PostId);

                Reply newReply = new Reply()
                {
                    Content = ReplyContent,
                    Post = currentPost,
                    User = currentUser,
                    Time = DateTime.Now
                };

                replyRepository.Add(newReply);

                if (returnUrl != null)
                    return Redirect(returnUrl);

                return RedirectToAction("Index", "Post");
            }
            catch
            {
                return RedirectToAction("Index", "Post");
            }
        }

    }
}

SocialMedia/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SocialMedia.Models;
using SocialMedia.ViewModels;
using SocialMedia.Repositories;

namespace SocialMedia.Controllers
{
    public class UserController : Controller
    {
        UserRepository _userRepository = RepositoryFactory.GetUserRepository();

        /// <summary>
        /// GET: /User/
        /// </summary>
        /// <returns>The ActionResult.</returns>
        [Authorize]
        public ActionResult Index()
        {
            var user = this.User;

            var allUser = _userRepository.All();

            return View(allUser);
        }

        /// <summary>
        /// GET: /User/Feed/1
        /// </summary>
        /// <param name="id">The id of the user</param>
        /// <returns>The ActionResult. </returns>
        [Authorize]
        public ActionResult Feed(int id)
        {
            UserRepository userRepo = RepositoryFactory.GetUserRepository();
            PostRepository postRepo = RepositoryFactory.GetPostRepository();

            User currentUser = userRepo.GetUserById(id);
            List<Post> postsByUser = postRepo.GetPostsByUserId(id);

            UserFeedModel feedModel = new UserFeedModel(currentUser, postsByUser);

            return View(feedModel);
        }

        /// <summary>
        /// POST: /User/Search. 
        /// </summary>
        /// <param name="UserName">The complete or partial username to search for.</param>
        /// <returns>The ActionResult.</returns>
        [HttpPost]
        [Authorize]
        public ActionResult Search(string UserName)
        {
            System.Diagnostics.Debug.WriteLine("UserName:" + UserName);

            var foundUsers = _userRepository.SearchByUserName(UserName);
            
            System.Diagnostics.Debug.WriteLine("foundUsers size:" + foundUsers.Count().ToString());

            return View("Index", foundUsers);
        }

    }
}

SocialMedia/Views/User/Feed.cshtml
@model SocialMedia.ViewModels.UserFeedModel

@{
    ViewBag.Title = "User feed";

    SocialMedia.Repositories.ReplyRepository _replyRepository = SocialMedia.Repositories.RepositoryFactory.GetReplyRepository();
    
    SocialMedia.Repositories.UserRepository _userRepository = SocialMedia.Repositories.RepositoryFactory.GetUserRepository();
    
    User currentUser = _userRepository.GetByUserName(User.Identity.Name);

    SocialMedia.Repositories.LikeRepository _likeRepository = SocialMedia.Repositories.RepositoryFactory.GetLikeRepository();    
    
}

<hgroup class="title">
    <h1>Feed.</h1>
    <h2>Posts made by @Model.User.Username</h2>
</hgroup>

<br />

@foreach (Post post in @Model.PostList)
{
    <div class="feed-wrapper clear-fix">
        <div class="feed-profile-img">
            <img width="64"
                 height="64"
                 align="middle"
                 alt="Gravatar"
                 src="http://www.gravatar.com/avatar/@post.User.emailHash()" />
        </div>
        <div class="feed-content-container">
            <div class="feed-content-firstrow">@post.User.Username <span class="feed-content-time">&raquo; @post.Time</span> </div>
            <div class="feed-content-main">@post.Content</div>
            <div class="feed-content-actions">               
                @if (!_likeRepository.UserLikesPost(currentUser, post))
                {
                    using (Html.BeginForm("Add", "Like", FormMethod.Post, new { id = "likePost" + @post.Id }))
                    {
                        @Html.Hidden("ReturnUrl", HttpContext.Current.Request.Url.AbsolutePath);
                    @Html.Hidden("UserId", @currentUser.Id)
                    @Html.Hidden("PostId", @post.Id)
                    }
                    <a href="#" onclick="document.getElementById('likePost' + @post.Id).submit();">Like</a>
                }
                else
                {
                    using (Html.BeginForm("Remove", "Like", FormMethod.Post, new { id = "unLikePost" + @post.Id }))
                    {
                        @Html.Hidden("ReturnUrl", HttpContext.Current.Request.Url.AbsolutePath);
                    @Html.Hidden("UserId", @currentUser.Id)
                    @Html.Hidden("PostId", @post.Id)
                    }
                    <a href="#" onclick="document.getElementById('unLikePost' + @post.Id).submit();">Unlike</a>
                }
                -
                @_likeRepository.GetNumberOfLikesByPost(post.Id) has liked this post
            </div>
        </div>
        <div class="clear-fix"></div>
        <div class="feed-comments-wrapper">
            <div class="feed-comments-img">
                <img alt="Gravatar" src="http://www.gravatar.com/avatar/@Model.User.emailHash()" />
            </div>
            <div class="feed-comments-form">
                @using (Html.BeginForm("Add", "Reply"))
                {
                    @Html.Hidden("ReturnUrl", HttpContext.Current.Request.Url.AbsolutePath);
                    @Html.Hidden("UserId", currentUser.Id)
                    @Html.Hidden("PostId", @post.Id)
                    @*@Html.TextBoxFor(m => m.PostContent, new { placeholder = "Reply to this post" })*@
                    @Html.TextBox("ReplyContent", "", new { placeholder = "Reply to this post" })
                    <input type="submit" value="Reply" />
                }
            </div>
        </div>
        @{ List<Reply> postReplies = _replyRepository.GetRepliesByPost(post.Id); }
        @foreach (Reply reply in postReplies)
        {
            <div class="feed-comments-wrapper">
                <div class="feed-comments-img" style="margin-top: 4px;">
                    <img alt="Gravatar" src="http://www.gravatar.com/avatar/@reply.User.emailHash()" />
                </div>
                <div class="feed-comments-form">
                    <span class="feed-comment-username">@reply.User.Username</span> <span class="feed-comment-time">&raquo; @reply.Time</span><br />
                    <span>@reply.Content</span>
                </div>
            </div>
        }
    </div>

    <div class="feed-separator"></div>
}

SocialMedia/Views/User/Index.cshtml
@model IEnumerable<SocialMedia.Models.User>

@{
    ViewBag.Title = "Users";

    SocialMedia.Repositories.FollowRepository _followRepository = SocialMedia.Repositories.RepositoryFactory.GetFollowRepository();

    SocialMedia.Repositories.UserRepository _userRepository = SocialMedia.Repositories.RepositoryFactory.GetUserRepository();
    User currentUser = _userRepository.GetByUserName(User.Identity.Name);
}
<hgroup class="title">
    <h1>Users.</h1>
    <h2>All registered users</h2>
</hgroup>

<div class="user-search">
    @using (Html.BeginForm("Search", "User"))
    {
        @Html.TextBox("UserName", "", new { placeholder = "Search for users to follow" })
        <input type="submit" value="Search" />
    }
</div>

@foreach (var user in Model) {

    if (user.Id == currentUser.Id)
    {
        continue;
    }

    <div class="user-list-container">
        <div class="user-list-img">
            <img width="64"
                 height="64"
                 alt="Gravatar"
                 src="http://www.gravatar.com/avatar/@user.emailHash()" />
        </div>
        <div class="user-info-container">
            <div class="user-info-name">@Html.ActionLink(user.Username, "Feed", "User", new { id = user.Id }, null)</div>
            <div class="user-follow-button">
                @if (_followRepository.IsFollowing(@currentUser.Id, @user.Id))
                {
                    using (Html.BeginForm("Remove", "Follow"))
                    {
                        @Html.Hidden("ReturnUrl", HttpContext.Current.Request.Url.AbsolutePath);
                        @Html.Hidden("FollowedUser", @user.Id)
                        @Html.Hidden("FollowsUser", @currentUser.Id)
                        <input type="submit" value="Unfollow" />    
                    }
                }
                else
                {
                    using (Html.BeginForm("Add", "Follow"))
                    {
                        @Html.Hidden("ReturnUrl", HttpContext.Current.Request.Url.AbsolutePath);
                        @Html.Hidden("FollowedUser", @user.Id)
                        @Html.Hidden("FollowsUser", @currentUser.Id)
                        <input type="submit" value="Follow" />
                    }
                }
            </div>
            <div class="user-info-mail">@user.Email</div>
        </div>
        
    </div>
}