SocialMedia/Controllers/FollowController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SocialMedia.Repositories;
using SocialMedia.Models;

namespace SocialMedia.Controllers
{
    public class FollowController : Controller
    {
        //
        // GET: /Follow/
        public ActionResult Index()
        {
            return View();
        }

        //
        // POST: /Follow/Add
        [HttpPost]
        public ActionResult Add(int FollowedUser, int FollowsUser, string ReturnUrl)
        {
            try
            {
                FollowRepository followRepository = RepositoryFactory.GetFollowRepository();
                UserRepository userRepository = RepositoryFactory.GetUserRepository();

                User userFollows = userRepository.GetUserById(FollowsUser);
                User userFollowed = userRepository.GetUserById(FollowedUser);

                Follow newFollow = new Follow()
                {
                    UserFollowed = userFollowed,
                    UserFollows = userFollows
                };

                followRepository.Add(newFollow);

                return Redirect(ReturnUrl);
            }
            catch
            {
                return Redirect(ReturnUrl);
            }
        }

        //
        // POST: /Follow/Remove
        [HttpPost]
        public ActionResult Remove(int FollowedUser, int FollowsUser, string ReturnUrl)
        {
            try
            {
                FollowRepository followRepository = RepositoryFactory.GetFollowRepository();
                UserRepository userRepository = RepositoryFactory.GetUserRepository();

                User userFollows = userRepository.GetUserById(FollowsUser);
                User userFollowed = userRepository.GetUserById(FollowedUser);

                followRepository.Remove(userFollows.Id, userFollowed.Id);

                return Redirect(ReturnUrl);
            }
            catch
            {
                return Redirect(ReturnUrl);
            }
        }

    }
}

SocialMedia/Controllers/PostController.cs
using SocialMedia.Models;
using SocialMedia.Repositories;
using SocialMedia.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SocialMedia.Controllers
{
    public class PostController : Controller
    {
        //
        // GET: /Post/
        [Authorize]
        public ActionResult Index()
        {

            // Get data

            SocialMedia.Repositories.UserRepository userRepository = SocialMedia.Repositories.RepositoryFactory.GetUserRepository();
            SocialMedia.Repositories.ReplyRepository replyRepository = SocialMedia.Repositories.RepositoryFactory.GetReplyRepository();
            SocialMedia.Repositories.LikeRepository likeRepository = SocialMedia.Repositories.RepositoryFactory.GetLikeRepository();
            SocialMedia.Repositories.PostRepository postRepository = SocialMedia.Repositories.RepositoryFactory.GetPostRepository();

            User currentUser = userRepository.GetByUserName(User.Identity.Name);
            
            //var allPosts = _postRepository.All();
            var allPosts = postRepository.GetFollowedPosts(currentUser);

            foreach (Post post in allPosts)
            {
                // Retrieve all replies for this post
                List<Reply> replies = replyRepository.GetRepliesByPost(post.Id);

                // Retrieve the number of likes for this post
                List<Like> likes = likeRepository.GetLikesByPost(post.Id);

                // Add the replies and the number of likes to the post object
                post.Replies.AddRange(replies);
                post.Likes.AddRange(likes);
            }

            // Fill the FeedModel with all data
            FeedModel feedModel = new FeedModel
            {
                AllPosts = allPosts,
                CurrentUser = currentUser
            };
   

            // Return view with ViewModel as parameter

            return View(feedModel);
        }

        //
        // GET: /Post/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        //
        // GET: /Post/Add
        public ActionResult Add()
        {
            return View();
        }

        //
        // POST: /Post/Add
        [HttpPost]
        public ActionResult Add(int UserId, string PostContent)
        {
            try
            {
                UserRepository userRepository = RepositoryFactory.GetUserRepository();
                PostRepository postRepository = RepositoryFactory.GetPostRepository();

                User currentUser = userRepository.GetUserById(UserId);

                Post newPost = new Post()
                {
                    Content = PostContent,
                    User = currentUser,
                    Time = DateTime.Now
                };

                postRepository.Add(newPost);

                return RedirectToAction("Index");
            }
            catch
            {
                return RedirectToAction("Index");
            }
        }

        //
        // GET: /Post/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        //
        // POST: /Post/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Post/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        //
        // POST: /Post/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

SocialMedia/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SocialMedia.Models;
using SocialMedia.ViewModels;
using SocialMedia.Repositories;

namespace SocialMedia.Controllers
{
    public class UserController : Controller
    {
        UserRepository _userRepository = RepositoryFactory.GetUserRepository();

        /// <summary>
        /// GET: /User/
        /// </summary>
        /// <returns>The ActionResult.</returns>
        [Authorize]
        public ActionResult Index()
        {
            var user = this.User;

            var allUser = _userRepository.All();

            return View(allUser);
        }

        /// <summary>
        /// GET: /User/Feed/1
        /// </summary>
        /// <param name="id">The id of the user</param>
        /// <returns>The ActionResult. </returns>
        [Authorize]
        public ActionResult Feed(int id)
        {
            UserRepository userRepo = RepositoryFactory.GetUserRepository();
            PostRepository postRepo = RepositoryFactory.GetPostRepository();

            User currentUser = userRepo.GetUserById(id);
            List<Post> postsByUser = postRepo.GetPostsByUserId(id);

            UserFeedModel feedModel = new UserFeedModel(currentUser, postsByUser);

            return View(feedModel);
        }

        /// <summary>
        /// POST: /User/Search. 
        /// </summary>
        /// <param name="UserName">The complete or partial username to search for.</param>
        /// <returns>The ActionResult.</returns>
        [HttpPost]
        [Authorize]
        public ActionResult Search(string UserName)
        {
            System.Diagnostics.Debug.WriteLine("UserName:" + UserName);

            var foundUsers = _userRepository.SearchByUserName(UserName);
            
            System.Diagnostics.Debug.WriteLine("foundUsers size:" + foundUsers.Count().ToString());

            return View("Index", foundUsers);
        }

    }
}

SocialMedia/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title - Kvittr</title>
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <meta name="viewport" content="width=device-width" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <header>
        <div id="menu-bar">
            <div id="menu-bar-inner">
                <div class=" float-left">
                    <a style="float: left;" href="/"><img src="~/Images/kvittr_logo.png" alt="Kvittr logo" /></a>
                    <nav style="float: left;">
                        <ul id="menu">
                            <a href="@Url.Action("Index", "Home")"><li>Home</li></a>
                             @if (this.User.Identity.IsAuthenticated)
                             {
                                <a href="@Url.Action("Index", "Post")"><li>Feed</li></a>
                                <a href="@Url.Action("Index", "Follow")"><li>Following</li></a>
                                <a href="@Url.Action("Index", "User")"><li>All users</li></a>
                            }
                        </ul>
                    </nav>
                </div>
                <div class="float-right">
                    <section id="login">
                        @Html.Partial("_LoginPartial")
                    </section>
                </div>
            </div>
        </div>
    </header>

    <div id="body">
        <section class="content-wrapper main-content clear-fix">
            <div class="main-content-left">@RenderBody()</div>
            <div class="main-content-right">@Html.Partial("_SidebarPartial")</div>
        </section>
    </div>
    <footer>
        <div>
            <p>&copy; @DateTime.Now.Year - Kvittr</p>
        </div>
    </footer>

    @Scripts.Render("~/bundles/jquery")
    @RenderSection("scripts", required: false)
</body>
</html>

SocialMedia/Views/Shared/_SidebarPartial.cshtml
<hgroup class="title"><h1>Sidebar.</h1></hgroup>
<ul>
    <li><a href="/">Länk 1</a></li>
    <li><a href="/">Länk 2</a></li>
    <li><a href="/">Länk 3</a></li>
    <li><a href="/">Länk 4</a></li>
</ul>